# **Assignment No - 1**

---
**Name** - Purva Ramesh Wagh .
**Roll No** - EN23107132 .
**Class** - TY(B) .
**Batch** - B

---
**Title -**
Identify a real-world problem in a specific industry (e.g., Agriculture, Healthcare, Finance, Education, or Retail) and propose an AI-driven solution. Outline the problem statement, AI methodology, expected impact, and feasibility of implementation.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("agriculture_dataset.csv")

In [ ]:
df

,High_Resolution_RGB,Multispectral_Images,Thermal_Images,Temporal_Images,Spatial_Resolution,GPS_Coordinates,Field_Boundaries,Elevation_Data,Canopy_Coverage,NDVI,...,Weed_Coverage,Pest_Damage,Crop_Growth_Stage,Expected_Yield,Crop_Type,Ground_Truth_Segmentation,Bounding_Boxes,Water_Flow,Drainage_Features,Crop_Health_Label
0,0,0,0,0,0.667324,201538,3,28.207634,8.046926,0.676945,...,1.922274,84,2,2540.784327,Wheat,1,5,41.771884,0,1
1,1,1,0,0,1.459000,215854,3,82.335147,147.512332,0.414781,...,4.851381,56,3,3227.617025,Wheat,0,1,27.564635,0,1
2,0,0,0,0,0.500442,890802,3,83.865629,30.246527,0.723610,...,5.974859,38,1,4609.938146,Maize,1,8,29.510836,0,1
3,0,0,0,0,1.865161,605584,3,20.747905,6.857820,0.405611,...,2.100598,27,2,1409.716754,Maize,0,1,34.822855,0,0
4,0,1,1,1,1.392331,871732,3,22.588815,26.168558,0.465992,...,3.025669,84,4,3905.312588,Rice,0,2,15.493255,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212014,0,0,0,0,1.613700,257270,3,99.854648,39.864640,0.460258,...,2.406950,5,2,2974.199519,Maize,0,8,45.866021,0,0
212015,0,0,0,0,2.167963,875693,3,41.523453,20.314558,0.196781,...,2.443758,38,2,3134.666651,Maize,1,5,0.642406,0,1
212016,0,0,0,0,1.553286,159572,3,40.316397,149.342415,0.455641,...,1.394352,37,3,3770.711312,Maize,0,3,23.734456,0,0
212017,0,0,0,0,1.550687,859553,3,25.684100,21.912619,0.243414,...,4.573550,2,1,3263.395842,Wheat,0,4,42.983774,0,1
212018,0,0,0,0,1.409110,910100,2,98.958476,104.490379,0.571688,...,0.928552,30,2,3760.457624,Wheat,0,5,43.663320,1,0

In [ ]:
df.isnull().sum()

High_Resolution_RGB          0
Multispectral_Images         0
Thermal_Images               0
Temporal_Images              0
Spatial_Resolution           0
GPS_Coordinates              0
Field_Boundaries             0
Elevation_Data               0
Canopy_Coverage              0
NDVI                         0
SAVI                         0
Chlorophyll_Content          0
Leaf_Area_Index              0
Crop_Stress_Indicator        0
Temperature                  0
Humidity                     0
Rainfall                     0
Wind_Speed                   0
Soil_Moisture                0
Soil_pH                      0
Organic_Matter               0
Pest_Hotspots                0
Weed_Coverage                0
Pest_Damage                  0
Crop_Growth_Stage            0
Expected_Yield               0
Crop_Type                    0
Ground_Truth_Segmentation    0
Bounding_Boxes               0
Water_Flow                   0
Drainage_Features            0
Crop_Health_Label            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212019 entries, 0 to 212018
Data columns (total 32 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   High_Resolution_RGB        212019 non-null  int64
 1   Multispectral_Images       212019 non-null  int64
 2   Thermal_Images             212019 non-null  int64
 3   Temporal_Images            212019 non-null  int64
 4   Spatial_Resolution         212019 non-null  float64
 5   GPS_Coordinates            212019 non-null  int64
 6   Field_Boundaries           212019 non-null  int64
 7   Elevation_Data             212019 non-null  float64
 8   Canopy_Coverage            212019 non-null  float64
 9   NDVI                       212019 non-null  float64
 10  SAVI                       212019 non-null  float64
 11  Chlorophyll_Content        212019 non-null  float64
 12  Leaf_Area_Index            212019 non-null  float64
 13  Crop_Stress_Indicator      212019 non-null  int64
 14  Temperature                212019 non-null  float64
 15  Humidity                   212019 non-null  float64
 16  Rainfall                   212019 non-null  float64
 17  Wind_Speed                 212019 non-null  float64
 18  Soil_Moisture              212019 non-null  float64
 19  Soil_pH                    212019 non-null  float64
 20  Organic_Matter             212019 non-null  float64
 21  Pest_Hotspots              212019 non-null  int64
 22  Weed_Coverage              212019 non-null  float64
 23  Pest_Damage                212019 non-null  int64
 24  Crop_Growth_Stage          212019 non-null  int64
 25  Expected_Yield             212019 non-null  float64
 26  Crop_Type                  212019 non-null  object
 27  Ground_Truth_Segmentation  212019 non-null  int64
 28  Bounding_Boxes             212019 non-null  int64
 29  Water_Flow                 212019 non-null  float64
 30  Drainage_Features          212019 non-null  int64
 31  Crop_Health_Label          212019 non-null  int64
dtypes: float64(17), int64(14), object(1)
memory usage: 51.8+ MB

In [ ]:
df.describe()

,High_Resolution_RGB,Multispectral_Images,Thermal_Images,Temporal_Images,Spatial_Resolution,GPS_Coordinates,Field_Boundaries,Elevation_Data,Canopy_Coverage,NDVI,...,Pest_Hotspots,Weed_Coverage,Pest_Damage,Crop_Growth_Stage,Expected_Yield,Ground_Truth_Segmentation,Bounding_Boxes,Water_Flow,Drainage_Features,Crop_Health_Label
count,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,...,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000,212019.000000
mean,0.200232,0.299714,0.399492,0.100430,1.200244,550433.748268,2.599946,54.948326,49.942370,0.500288,...,0.149062,2.859558,49.471429,2.504073,3003.456310,0.299884,4.504059,25.029792,0.200147,0.698985
std,0.400175,0.458134,0.489795,0.300573,0.499427,260335.476601,0.663463,25.969531,49.925445,0.149984,...,0.356151,1.598052,28.891332,1.119026,797.669541,0.458208,2.872436,14.440683,0.400111,0.458701
min,0.000000,0.000000,0.000000,0.000000,-0.959732,100003.000000,1.000000,10.000034,0.000237,-0.165259,...,0.000000,0.001940,0.000000,1.000000,-468.653721,0.000000,0.000000,0.000051,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.862755,324279.000000,2.000000,32.550718,14.368852,0.398988,...,0.000000,1.617502,24.000000,2.000000,2467.295493,0.000000,2.000000,12.516200,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,1.199967,550668.000000,3.000000,54.840251,34.544415,0.500420,...,0.000000,2.642263,50.000000,3.000000,3003.479378,0.000000,4.000000,25.036105,0.000000,1.000000
75%,0.000000,1.000000,1.000000,0.000000,1.538014,776122.000000,3.000000,77.443205,69.375661,0.600887,...,0.000000,3.899610,74.000000,4.000000,3539.738947,1.000000,7.000000,37.532306,0.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,3.344946,999986.000000,3.000000,99.999944,582.456962,1.158040,...,1.000000,9.344244,99.000000,4.000000,6684.320978,1.000000,9.000000,49.999447,1.000000,1.000000

In [ ]:
x = df[['Temperature', 'Humidity', 'Rainfall', 'Soil_Moisture']]

In [ ]:
y = df['Crop_Health_Label']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()

In [ ]:
lr.fit(x_train,y_train)

LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [ ]:
lr_score = lr.score(x_train, y_train)
print("lr:", lr_score)

lr: 0.6989476166612623

In [ ]:
lr_pred=lr.predict(x_test)

In [ ]:
lr_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
ac=accuracy_score(y_test,lr_pred)

In [ ]:
ac

0.6991321573436469

In [ ]:
pc=precision_score(y_test,lr_pred)

In [ ]:
pc

0.6991321573436469

In [ ]:
rc=recall_score(y_test,lr_pred)

In [ ]:
rc

1.0

In [ ]:
f1=f1_score(y_test,lr_pred)
f1

0.8229285218598196

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gb=GaussianNB()

In [ ]:
gb.fit(x_train,y_train)

GaussianNB()

In [ ]:
lr_pred=lr.predict(x_test)

In [ ]:
lr_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
ac=accuracy_score(y_test,lr_pred)
ac

0.6991321573436469

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
mn=MultinomialNB()

In [ ]:
mn.fit(x_train,y_train)

MultinomialNB()

In [ ]:
ac=accuracy_score(y_test,lr_pred)
ac

0.6991321573436469