# **Assignment No - 3**

---
**Name** - Purva Ramesh Wagh .
**Roll No** - EN23107132 .
**Class** - TY(B) .
**Batch** - B

---
**Title -**
Develop a sentiment analysis model to analyze customer reviews of products or services.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv("swiggy1.csv")
df2 = pd.read_csv("zomato1.csv")

In [ ]:
df1

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion
0,Swiggy,2023-07-24 09:57:40,I have been using swiggy for a long time and I...,2,103,"Hey there, we apologize for the inconvenience ...",2023-07-24 10:02:21,4.37.2
1,Swiggy,2023-07-23 10:35:23,Worst experiences I'm having with the app for ...,1,12,"Hello, we would like to know more about it. Pl...",2023-07-23 10:42:22,4.37.2
2,Swiggy,2023-07-24 14:48:26,The best foolishing app with offers. The app o...,1,7,We are sorry to let you down. Please write to ...,2023-07-24 14:52:22,4.37.2
3,Swiggy,2023-07-07 08:26:00,Title: Disappointing Experience with Swiggy In...,1,85,"Hey there, we are sorry to have put you throug...",2023-07-07 08:32:20,4.36.1
4,Swiggy,2023-07-19 07:40:05,Worst ever experience. I ordered from instamar...,1,29,We're apologetic about this experience you've ...,2023-07-19 07:42:22,4.36.3
...,...,...,...,...,...,...,...,...
200786,Swiggy,2019-01-09 08:24:54,Very Good Experience with Swiffy,5,0,"Hey Navjyot, we're pleased that you enjoyed yo...",2019-01-09 08:33:44,2.3.13
200787,Swiggy,2019-11-30 15:06:54,Good offers. Best food,5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-30 15:16:20,3.12.0
200788,Swiggy,2019-12-10 11:49:51,It's real awesome fast delivery,5,0,"Hey, thanks for the rating! This motivates us ...",2019-12-10 11:56:12,3.12.0
200789,Swiggy,2019-11-11 11:32:01,"Super app, and healful",5,0,"Hey, thanks for the rating! This motivates us ...",2019-11-11 11:36:18,3.10.0
200790,Swiggy,2019-11-18 20:04:15,very user friendly,5,0,"Hi Arnav, thank you for the perfect stars and ...",2019-11-18 20:09:21,3.11.1

In [ ]:
df2

,App,review_date,review_description,rating,thumbsUpCount,developer_response,developer_response_date,appVersion
0,Zomato,2023-07-23 15:52:11,"So basically , it's the best approach you'll e...",5,99,NaN,NaN,17.6.0
1,Zomato,2023-07-08 04:32:18,Always Late Delivery. No change. Late delivery...,1,416,"Hi Magesh, sorry to hear about that. Please wr...",2023-07-08 11:35:20,17.5.8
2,Zomato,2023-07-24 21:14:56,"This app is froude with their zomato gold, i h...",1,1,"Hi there, we are really sorry for the bad expe...",2023-07-24 21:15:52,17.6.2
3,Zomato,2023-07-24 17:07:55,I tried 100 times adding an alternate number i...,1,1,"Hi there, we are really sorry for the bad expe...",2023-07-24 17:09:50,17.6.2
4,Zomato,2023-07-22 13:28:26,"In recent years, Zomato support has become les...",1,30,"Hi Shaik, we're sorry to hear that. We are con...",2023-07-23 10:29:50,17.6.2
...,...,...,...,...,...,...,...,...
264864,Zomato,2020-03-12 15:11:00,App has Upgraded really well,5,0,NaN,NaN,14.4.8
264865,Zomato,2019-04-14 20:02:48,good job by zomato n rider too,4,0,NaN,NaN,13.2.6
264866,Zomato,2021-10-03 14:41:51,Nice service&cashback is very good,5,0,NaN,NaN,16.1.1
264867,Zomato,2023-05-19 14:37:57,Gold is Gold!,5,0,NaN,NaN,17.5.0
264868,Zomato,2020-01-29 17:57:16,Good user interface,5,0,NaN,NaN,14.3.9

In [ ]:
def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating <= 2:
        return "Negative"
    else:
        return "Neutral"

In [ ]:
def sentiment_accuracy(df, name="Dataset"):

    from sklearn.model_selection import train_test_split
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import accuracy_score, classification_report

    print("\nProcessing:", name)

    df = df[['review_description', 'rating']].copy()
    df = df.dropna()

    print("Number of samples:", len(df))

    df['sentiment'] = df['rating'].apply(label_sentiment)

    X_train, X_test, y_train, y_test = train_test_split(
        df['review_description'],
        df['sentiment'],
        test_size=0.2,
        random_state=42
    )

    tfidf = TfidfVectorizer(stop_words='english', max_features=3000)

    X_train_tfidf = tfidf.fit_transform(X_train)
    X_test_tfidf = tfidf.transform(X_test)

    model = LogisticRegression(max_iter=2000, n_jobs=-1)
    model.fit(X_train_tfidf, y_train)

    y_pred = model.predict(X_test_tfidf)

    acc = accuracy_score(y_test, y_pred)

    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred))

    return acc

In [ ]:
swiggy_acc = sentiment_accuracy(df1, "Swiggy")
zomato_acc = sentiment_accuracy(df2, "Zomato")

print("\nFinal Results")
print("Swiggy Accuracy:", swiggy_acc)
print("Zomato Accuracy:", zomato_acc)

Processing: Swiggy
Number of samples: 200791
Accuracy: 0.8961129510196967
              precision    recall  f1-score   support

    Negative       0.89      0.95      0.92     22166
     Neutral       0.30      0.01      0.02      1740
    Positive       0.90      0.91      0.91     16253

    accuracy                           0.90     40159
   macro avg       0.70      0.63      0.62     40159
weighted avg       0.87      0.90      0.88     40159


Processing: Zomato
Number of samples: 264869
Accuracy: 0.8981953411107335
              precision    recall  f1-score   support

    Negative       0.89      0.95      0.92     24797
     Neutral       0.29      0.01      0.03      2293
    Positive       0.91      0.93      0.92     25884

    accuracy                           0.90     52974
   macro avg       0.70      0.63      0.62     52974
weighted avg       0.87      0.90      0.88     52974


Final Results
Swiggy Accuracy: 0.8961129510196967
Zomato Accuracy: 0.8981953411107335